export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'

export const USER_DETAILS_REQUESTED = 'USER_DETAILS_REQUESTED'
export const USER_DETAILS_SUCCESS = 'USER_STATE_SUCCESS'

export const LIST_SHOPS_REQUESTED = 'LIST_SHOPS_REQUESTED'
export const LIST_SHOPS_SUCCESS = 'LIST_SHOPS_SUCCESS'