export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'

export const USER_DETAILS_REQUESTED = 'USER_DETAILS_REQUESTED'
export const USER_DETAILS_SUCCESS = 'USER_STATE_SUCCESS'

export const LIST_SHOPS_REQUESTED = 'LIST_SHOPS_REQUESTED'
export const LIST_SHOPS_SUCCESS = 'LIST_SHOPS_SUCCESS'

export const SEND_SUBSCRIPTIONREQUEST_REQUESTED = 'SEND_SUBSCRIPTION_REQUESTED'
export const SEND_SUBSCRIPTIONREQUEST_SUCCESS = 'SEND_SUBSCRIPTION_SUCCESS'

export const LIST_ADMINNOTIFICATIONS_REQUESTED = 'LIST_ADMINNOTIFICATIONS_REQUESTED'
export const LIST_ADMINNOTIFICATIONS_SUCCESS = 'LIST_ADMINNOTIFICATIONS_SUCCESS'

export const CHANGE_THEME = 'CHANGE_THEME'